"""initial_project_state_schema

Revision ID: 8500d29c55e0
Revises: 
Create Date: 2026-05-17 21:16:45.738220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8500d29c55e0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mechanics_db',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('mechanic_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dynamics_served', sa.JSON(), nullable=True),
    sa.Column('aesthetics_served', sa.JSON(), nullable=True),
    sa.Column('genre_affinity', sa.JSON(), nullable=True),
    sa.Column('conflicts_with', sa.JSON(), nullable=True),
    sa.Column('synergies_with', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanics_db_group_name'), 'mechanics_db', ['group_name'], unique=False)
    op.create_index('ix_mechanics_group_name', 'mechanics_db', ['group_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('ai_calls_count', sa.Integer(), nullable=False),
    sa.Column('ai_calls_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_plan'), 'users', ['plan'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project_stage', sa.String(length=30), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_algorithm_run', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_genre'), 'projects', ['genre'], unique=False)
    op.create_index(op.f('ix_projects_project_stage'), 'projects', ['project_stage'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('project_balance_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('balance_type', sa.String(length=30), nullable=True),
    sa.Column('overall_balance_score', sa.Float(), nullable=True),
    sa.Column('imbalance_count', sa.Integer(), nullable=True),
    sa.Column('element_count', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('elements', sa.JSON(), nullable=True),
    sa.Column('cost_power_curves', sa.JSON(), nullable=True),
    sa.Column('intransitive_matrix', sa.JSON(), nullable=True),
    sa.Column('nash_equilibrium', sa.JSON(), nullable=True),
    sa.Column('monte_carlo_results', sa.JSON(), nullable=True),
    sa.Column('machinations_results', sa.JSON(), nullable=True),
    sa.Column('pathologies', sa.JSON(), nullable=True),
    sa.Column('corrections', sa.JSON(), nullable=True),
    sa.Column('situational_values', sa.JSON(), nullable=True),
    sa.Column('full_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_balance_results_balance_type'), 'project_balance_results', ['balance_type'], unique=False)
    op.create_index(op.f('ix_project_balance_results_project_id'), 'project_balance_results', ['project_id'], unique=True)
    op.create_table('project_checklists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('readiness_level', sa.String(length=30), nullable=True),
    sa.Column('critical_issue_count', sa.Integer(), nullable=True),
    sa.Column('total_issue_count', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('mda_check', sa.JSON(), nullable=True),
    sa.Column('balance_check', sa.JSON(), nullable=True),
    sa.Column('narrative_check', sa.JSON(), nullable=True),
    sa.Column('economy_check', sa.JSON(), nullable=True),
    sa.Column('lens_check', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('remediation_plan', sa.JSON(), nullable=True),
    sa.Column('full_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_checklists_project_id'), 'project_checklists', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_checklists_readiness_level'), 'project_checklists', ['readiness_level'], unique=False)
    op.create_table('project_concepts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('subgenre', sa.String(length=100), nullable=True),
    sa.Column('primary_aesthetic', sa.String(length=50), nullable=True),
    sa.Column('usp', sa.Text(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('one_pager_data', sa.JSON(), nullable=True),
    sa.Column('aesthetic_profile', sa.JSON(), nullable=True),
    sa.Column('dynamics_profile', sa.JSON(), nullable=True),
    sa.Column('mechanic_set', sa.JSON(), nullable=True),
    sa.Column('validation_report', sa.JSON(), nullable=True),
    sa.Column('usp_candidates', sa.JSON(), nullable=True),
    sa.Column('core_loop_candidates', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_concepts_genre'), 'project_concepts', ['genre'], unique=False)
    op.create_index(op.f('ix_project_concepts_primary_aesthetic'), 'project_concepts', ['primary_aesthetic'], unique=False)
    op.create_index(op.f('ix_project_concepts_project_id'), 'project_concepts', ['project_id'], unique=True)
    op.create_table('project_core_loops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('structural_type', sa.String(length=30), nullable=True),
    sa.Column('structural_subtype', sa.String(length=50), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('hierarchy_depth', sa.Integer(), nullable=True),
    sa.Column('pathology_count', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('steps_data', sa.JSON(), nullable=True),
    sa.Column('inner_loops', sa.JSON(), nullable=True),
    sa.Column('outer_loops', sa.JSON(), nullable=True),
    sa.Column('meta_loop', sa.JSON(), nullable=True),
    sa.Column('loop_hierarchy', sa.JSON(), nullable=True),
    sa.Column('pathologies', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('validation_data', sa.JSON(), nullable=True),
    sa.Column('full_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_core_loops_project_id'), 'project_core_loops', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_core_loops_structural_type'), 'project_core_loops', ['structural_type'], unique=False)
    op.create_table('project_economies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('system_type', sa.String(length=30), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('has_pathology', sa.Boolean(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('resource_model', sa.JSON(), nullable=True),
    sa.Column('machinations_model', sa.JSON(), nullable=True),
    sa.Column('conversion_chains', sa.JSON(), nullable=True),
    sa.Column('pathologies', sa.JSON(), nullable=True),
    sa.Column('corrections', sa.JSON(), nullable=True),
    sa.Column('simulation_results', sa.JSON(), nullable=True),
    sa.Column('monetization_model', sa.JSON(), nullable=True),
    sa.Column('full_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_economies_project_id'), 'project_economies', ['project_id'], unique=True)
    op.create_index(op.f('ix_project_economies_system_type'), 'project_economies', ['system_type'], unique=False)
    op.create_table('project_gdds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=True),
    sa.Column('completeness_percent', sa.Float(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('visual_elements', sa.JSON(), nullable=True),
    sa.Column('consistency_issues', sa.JSON(), nullable=True),
    sa.Column('completeness_report', sa.JSON(), nullable=True),
    sa.Column('full_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_gdds_format'), 'project_gdds', ['format'], unique=False)
    op.create_index(op.f('ix_project_gdds_project_id'), 'project_gdds', ['project_id'], unique=True)
    op.create_table('project_mda_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('primary_aesthetic', sa.String(length=50), nullable=True),
    sa.Column('secondary_aesthetic', sa.String(length=50), nullable=True),
    sa.Column('overall_match', sa.Float(), nullable=True),
    sa.Column('iteration_count', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('target_dynamics', sa.JSON(), nullable=True),
    sa.Column('mechanic_set', sa.JSON(), nullable=True),
    sa.Column('observed_dynamics', sa.JSON(), nullable=True),
    sa.Column('predicted_aesthetics', sa.JSON(), nullable=True),
    sa.Column('match_scores', sa.JSON(), nullable=True),
    sa.Column('lens_validation', sa.JSON(), nullable=True),
    sa.Column('bond_validation', sa.JSON(), nullable=True),
    sa.Column('ludonarrative_check', sa.JSON(), nullable=True),
    sa.Column('machinations_model', sa.JSON(), nullable=True),
    sa.Column('simulation_results', sa.JSON(), nullable=True),
    sa.Column('full_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_mda_profiles_primary_aesthetic'), 'project_mda_profiles', ['primary_aesthetic'], unique=False)
    op.create_index(op.f('ix_project_mda_profiles_project_id'), 'project_mda_profiles', ['project_id'], unique=True)
    op.create_table('project_progressions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('total_levels', sa.Integer(), nullable=True),
    sa.Column('tier_count', sa.Integer(), nullable=True),
    sa.Column('curve_type', sa.String(length=30), nullable=True),
    sa.Column('target_duration_hours', sa.Float(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('macro_model', sa.JSON(), nullable=True),
    sa.Column('tier_model', sa.JSON(), nullable=True),
    sa.Column('curves', sa.JSON(), nullable=True),
    sa.Column('content_plan', sa.JSON(), nullable=True),
    sa.Column('economy_link', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('full_profile', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_progressions_curve_type'), 'project_progressions', ['curve_type'], unique=False)
    op.create_index(op.f('ix_project_progressions_project_id'), 'project_progressions', ['project_id'], unique=True)
    op.create_table('prompt_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('prompt_id', sa.String(length=100), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('from_cache', sa.Boolean(), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_logs_created_at'), 'prompt_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_logs_project_id'), 'prompt_logs', ['project_id'], unique=False)
    op.create_index('ix_prompt_logs_prompt_created', 'prompt_logs', ['prompt_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_prompt_logs_prompt_id'), 'prompt_logs', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_logs_user_created', 'prompt_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_prompt_logs_user_id'), 'prompt_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_logs_user_id'), table_name='prompt_logs')
    op.drop_index('ix_prompt_logs_user_created', table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_prompt_id'), table_name='prompt_logs')
    op.drop_index('ix_prompt_logs_prompt_created', table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_project_id'), table_name='prompt_logs')
    op.drop_index(op.f('ix_prompt_logs_created_at'), table_name='prompt_logs')
    op.drop_table('prompt_logs')
    op.drop_index(op.f('ix_project_progressions_project_id'), table_name='project_progressions')
    op.drop_index(op.f('ix_project_progressions_curve_type'), table_name='project_progressions')
    op.drop_table('project_progressions')
    op.drop_index(op.f('ix_project_mda_profiles_project_id'), table_name='project_mda_profiles')
    op.drop_index(op.f('ix_project_mda_profiles_primary_aesthetic'), table_name='project_mda_profiles')
    op.drop_table('project_mda_profiles')
    op.drop_index(op.f('ix_project_gdds_project_id'), table_name='project_gdds')
    op.drop_index(op.f('ix_project_gdds_format'), table_name='project_gdds')
    op.drop_table('project_gdds')
    op.drop_index(op.f('ix_project_economies_system_type'), table_name='project_economies')
    op.drop_index(op.f('ix_project_economies_project_id'), table_name='project_economies')
    op.drop_table('project_economies')
    op.drop_index(op.f('ix_project_core_loops_structural_type'), table_name='project_core_loops')
    op.drop_index(op.f('ix_project_core_loops_project_id'), table_name='project_core_loops')
    op.drop_table('project_core_loops')
    op.drop_index(op.f('ix_project_concepts_project_id'), table_name='project_concepts')
    op.drop_index(op.f('ix_project_concepts_primary_aesthetic'), table_name='project_concepts')
    op.drop_index(op.f('ix_project_concepts_genre'), table_name='project_concepts')
    op.drop_table('project_concepts')
    op.drop_index(op.f('ix_project_checklists_readiness_level'), table_name='project_checklists')
    op.drop_index(op.f('ix_project_checklists_project_id'), table_name='project_checklists')
    op.drop_table('project_checklists')
    op.drop_index(op.f('ix_project_balance_results_project_id'), table_name='project_balance_results')
    op.drop_index(op.f('ix_project_balance_results_balance_type'), table_name='project_balance_results')
    op.drop_table('project_balance_results')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_genre'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_plan'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_mechanics_group_name', table_name='mechanics_db')
    op.drop_index(op.f('ix_mechanics_db_group_name'), table_name='mechanics_db')
    op.drop_table('mechanics_db')
    # ### end Alembic commands ###
